version: '3.8'

services:
  trackingapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5060:7070"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TrackingDB=Server=localhost;Database=TrackingDB;User=sa;Password=123456aA*;TrustServerCertificate=True
      - HangfireDB=Server=localhost;Database=HangfireDB;User=sa;Password=123456aA*;TrustServerCertificate=True
    # depends_on:
      # - trackingdb
      # - hangfiredb

  # trackingdb:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=123456aA*
  #   ports:
  #     - "51433:1433"

  # hangfiredb:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=123456aA*
  #   ports:
  #     - "51434:1433"
