# # docker-compose.yml


# services:
#   trackingapi:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "5000:80"
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_URLS=http://+:80
#       - ConnectionStrings__TrackingDB=Server=host.docker.internal,51433;Database=TrackingDatabase;User=sa;Password=123456aA*;TrustServerCertificate=True
#       - ConnectionStrings__HangfireDB=Server=host.docker.internal,51434;Database=HangfireDatabase;User=sa;Password=123456aA*;TrustServerCertificate=True
#     extra_hosts:
#       - "host.docker.internal:host-gateway"

# networks:
#   default:
#     driver: bridge

services:
  trackingapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80" # Swagger ve API için
      - "5001:5001" # (İhtiyaç varsa) Hangfire için ek port
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__TrackingDB=Server=host.docker.internal,51433;Database=TrackingDatabase;User=sa;Password=123456aA*;TrustServerCertificate=True
      - ConnectionStrings__HangfireDB=Server=host.docker.internal,51434;Database=HangfireDatabase;User=sa;Password=123456aA*;TrustServerCertificate=True
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - tracking_network

networks:
  tracking_network:
    driver: bridge
